version: "3"
services:
  q-and-a:
    container_name: q_and_a_container
    build: ~/hackreactor/SDC-Q-and-A-Service/
    restart: always
    ports:
      - "3003:3003"
  postgres:
    image: postgres
    container_name: sdc_pg_container
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./my-db:/var/lib/postgresql/data
